apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura-service
spec:
  selector:
    app: conversao-temperatura
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
